### PR TITLE
refactoring the idea plugin so operators logic is taken out from gram…

### PR DESCRIPTION
**Pull request by sergio-castro**
…mar files.

### CODE REVIEW

**Comment by pmoura** [comment]
The DCO signature is missing. It's very easy. See https://github.com/probot/dco#how-it-works

**Comment by pmoura** [comment]
The files with meta-data for building the plug-in seem to have been deleted. Aren't they require to build the plug-in from sources?

**Comment by sergio-castro** [comment]
Too late :(. I gave back my two computers to tomtom already and will not
have a decent one until november. Also i am leaving for holidays now. I
will try to do it when i am back if you cannot to it in the meanwhile.

Cheers,

Sergio

**Comment by sergio-castro** [comment]
For some reason they were duplicated in two different places. Probably
related to the migration to gradle. I deleted the redundant one. You should
find another one with the same name somewhere else.

Cheers,

Sergio

**Comment by pmoura** [comment]
The files are definitely missing. There ins't anymore a `resources` directory. Enjoy your holidays. We will sort it out when you comeback.

**Comment by sergio-castro** [comment]
The entire directory was deleted because its relevant content (one file) is
somewhere else.

**Comment by pmoura** [comment]
All the `*.png` files are also deleted. Another odd finding is that the IDE (CE) doesn't offer to update the old 1.0.9 version of the plugin that I have installed. 1.0.11 is still reported as being reviewed in the website but that's not the case for 1.0.10.

**Comment by pmoura** [comment]
Downloading version 1.0.10 of the plugin and trying to install from disk in the latest CE of the IDE reports the plugin as being incompatible.

**Comment by pmoura** [comment]
After public discussion with @sergio-castro, the plugin source code is now available from its repository at https://github.com/java-prolog-connectivity/logtalk-intellij

**Pull request closed without merging**
