### PR TITLE
First version of the Logtalk pluging for IntelliJ IDEA.

### PR DESCRIPTION
**Pull request by sergio-castro**
Created the plugin in coding/idea.
I called the folder "idea" instead of "intellij" since the former is the folder name that IntelliJ uses by default.
Needed to modify a bit .gitignore to correctly ignore non-relevant Java or IntelliJ files.

### CODE REVIEW

**Comment by pmoura** [comment]
Thanks for the contribution. Sent you two mails with missing built-in directives, predicates, and operators w.r.t. syntax coloring. After adding them, simply commit in your fork and the changes will be added to this pull request automatically.

**Comment by sergio-castro** [comment]
thanks for your feedback !
I think the operators are recognized as such, but I just need to change the
color of them.
But the other keywords were indeed omitted.

Sergio

**Comment by sergio-castro** [comment]
Pushed. Will deploy a new version now.

Btw, it looks quite better with the theme Darcula (change the tem in the
appearence menu in the IntelliJ settings).

Sergio

**Comment by pmoura** [comment]
Superseded by #33.

**Pull request closed without merging**
