### PR TITLE
Adding code_metrics to developer tools.

### PR DESCRIPTION
**Pull request by eazar001**
Hello, please consider this submission of a code metrics tool for inclusion into the Logtalk developer tools framework. Thanks for your time and consideration.

### CODE REVIEW

**Comment by pmoura** [comment]
Please don't use `\c` for breaking long atoms. It causes portability problems with some of the backend Prolog compilers. Also, again due to portability concerns, ensure that no atom (used in the documentation) is longer than 255 characters.

**Comment by pmoura** [comment]
There are several code formatting issues, which are quite apparent when using the "Files changed" link in this page. Please see the "Source code layout and indentation" section at https://github.com/LogtalkDotOrg/logtalk3/wiki/Coding-Style-Guidelines

**Comment by pmoura** [comment]
Overall, and without having run the code yet, the tool looks good. Thanks! I hope that the minor issues found so far can be solved quickly to get the code ready to merge.

**Comment by eazar001** [comment]
@pmoura , thanks for your review. I'll try to fix the issues that you've found and commit their respective corrections.

**Comment by pmoura** [comment]
In the test set, you're using mainly the `test/1` dialect but there are also a few cases of the `test/2` dialect for queries that are expected to fail. As a matter of coding style, please consider converting those to the `test/1` dialect using `\+/1` in the test body.

**Comment by eazar001** [comment]
Apparently I had my editor set to soft tabs.

**Comment by pmoura** [comment]
The `dit` object uses a soft-cut (`*->/2`) but that's not a standard built-in predicate  and is only available in some of the Logtalk supported backend Prolog compilers. We'll need to replace it.

**Comment by pmoura** [comment]
Using relative paths such as `'./metrics/'` in definitions for the `logtalk_library_path/2` can rise portability issues as Prolog compilers use different interpretations of current working directory. Best to use `code_metrics('metrics/')`.

**Comment by pmoura** [comment]
Thanks for the quick fixes. I will review the updated version.

**Comment by pmoura** [comment]
In the `analysis` category, the predicates `entity_calls/4` and `entity_updates/4` should not assume that entity properties are returned using a fixed order.

**Comment by pmoura** [comment]
As Logtalk implements a single namespace for all entities, given that this tool will be used on loaded user code, it's a good idea to avoid generic entity names that can clash with user code. Thus, I suggest renaming the `analysis` category to e.g. `code_metrics_support` and the `metricp` to e.g. `code_metric_protocol`.

**Comment by eazar001** [comment]
> ... it's a good idea to avoid generic entity names that can clash with user code. 

Good point. I'll rename these entities to something else.

**Pull request merged**
