### PR TITLE
Fixing bug where no message output is displayed in code_metrics and renaming metric prototypes.

### PR DESCRIPTION
**Pull request by eazar001**
I forgot to change an entity name in `code_metrics.lgt`.

### CODE REVIEW

**Comment by pmoura** [comment]
Thanks. Can you also rename the individual metrics themselves? We forgot them when we talked about the renaming the main entities. Maybe use names that end with `_metric`?

**Comment by eazar001** [comment]
Oh right, sure I'll append `_metric` to the metric object names.

**Comment by eazar001** [comment]
Wait, don't merge yet. One more commit coming up, sorry.

**Comment by eazar001** [comment]
Ok, everything is updated now.

**Comment by pmoura** [comment]
Merged. Thanks!

**Comment by pmoura** [comment]
API documentation and diagrams also updated in 19c9805469ce3aee3a2107bbf4e50b37ef02d6ce.

**Pull request merged**
