### PR TITLE
Update trealla.pl

### PR DESCRIPTION
**Pull request by infradig**
This will be needed.

### CODE REVIEW

**Comment by pmoura** [comment]
The change you suggest will not work in general. Logtalk provides a native reflection API, which includes data about loaded files, and also portable libraries, notably for operating-system access. The predicates in these APIs are fully documented, including their templates (i.e. argument **type** information) and instantiation modes. Allowing double-quoted terms or lists of chars to slip in would break the contracts providing by those APIs. Thus, the solution here is to ensure, in the adapter file and elsewhere (e.g. in the [`os`](https://logtalk.org/library/library_index.html#os) portable library, that any calls to Trealla Prolog built-in predicates that do not return an atom (where an atom is expected) will be followed by any necessary conversion. You can see it already in the adapter file definition for the internal `'$lgt_current_directory'/1` predicate:

```logtalk
'$lgt_current_directory'(Directory) :-
	working_directory(Directory0, Directory0),
	atom_chars(Directory, Directory0).
```

The implicit generalization in the change you suggest may, just may, work when running Logtalk on Trealla Prolog (extensive test would be required) but most likely hurt the portability of Logtalk applications.

**Comment by infradig** [comment]
Fair enough.

**Comment by pmoura** [comment]
Thanks for understanding. Looking forward to have Logtalk running on Trealla Prolog.

**Comment by infradig** [comment]
You will need to do the same here...

'$lgt_expand_path'(Path, ExpandedPath) :-
    absolute_file_name(Path, ExpandedPath0, [expand(true)]),
    atom_chars(ExpandedPath, ExpandedPath0).

**Comment by pmoura** [comment]
Thanks. Updated adapter file pushed.

**Pull request closed without merging**
